### PR TITLE
Generic refactoring

### PR DESCRIPTION
**Pull request by AlexPresso**
This PR aims to help the VideoStation's patch and MediaServer's patch to work together (i.e. you want to patch VideoStation + MediaServer).

Changes:
- Make CodecPack (Advanced Media Extensions) patch standalone : CodecPack is not anymore relying on VideoStation's patched files to work. It's safer this way, as VideoStation can be removed without breaking CodecPack features.
- CodecPack patched `ffmpeg` files (`ffmpeg33`, `ffmpeg41` and/or `ffmpeg27`) are now trying with CodecPack default ffmpeg files before trying to use SynoCommunity's ffmpeg. Again, it's safer for other applications also relying on CodecPack's ffmpeg to work.
- Group gstreamer patched libraries and plugins into same directory to make it easier and safer to remove.
- Make the wrappers work in a more generic way
- Code cleaning

### CODE REVIEW

**Comment by AlexPresso** [comment]
Hey there,

If some people wants to test this PR, please follow these instructions:
- uninstall the patch : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- install the new patch `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/generic_refactor/patcher.sh | bash -s -- -a patch -b generic_refactor`

Please inform me of any issue you could have

**Comment by AlexPresso** [comment]
Tested OK on my DS218Play

**Comment by AlexPresso** [comment]
Hi @Fabian1601 ; @djhibee and @ner00
Sorry to ping you, but if you mind testing this new patcher using the previous comment procedure, it would be highly appreciated

**Comment by Fabian1601** [comment]
Hello Alex,

im already on it but as soon as it restarts in script videostation it reindexes all files.
It i start in the meantime the install script and it restarts videostation again it trashes all my database.
It just takes a Moment 😉

**Comment by AlexPresso** [comment]
Yeah it also happens to me sometimes ahah, I have to reindex everything, it's quite annoying, but I guess Synology don't want to work on fixing that

**Comment by Fabian1601** [comment]
So script ran smoothly and no problems so far. Playback is fine and i have a file in offline transcoding but it still needs about 20min to finish 👍

**Pull request merged**
