### PR TITLE
Improvements and Fix wrapping procedure on non ARMv8

### PR DESCRIPTION
**Pull request by AlexPresso**
- Add .gitignore
- Add motd.txt to display informational messages related to the patcher
- Refactor patcher.sh to add `-force-wrapper` option, motd, automatic codecpack's files patching (see #7 and #8)

### CODE REVIEW

**Comment by findstevehere** [comment]
Just tried the DTS wrapper but doesnt work on DSM220+ with DSM 7. Video Station won't play and wont reinstall or repair. Guess I will have to reinstall DSM.

**Comment by AlexPresso** [comment]
If you're using my patcher, you have to uninstall and reinstall both VideoStation and Advanced Media Extensions to remove the wrapper, as they both get patched.

It does enable all the mentioned codecs but I'm aware of an issue that affects transcoding of H.265 files (because of Advanced Media Extensions).

I'll add "uninstall / repair" instructions to the readme.
Please open an issue if you still have a problem on your DSM.

**Comment by findstevehere** [comment]
thanks a lot. So is it done? didnt do this last time. was I supposed to stop and start Video station?

**Comment by findstevehere** [comment]
oh wow awesome, it works! takes a little longer to load I think for an EAC3 audio file but plays!

thanks a lot

steve

**Comment by AlexPresso** [comment]
Yes, the patcher received a lot of improvements since the first version :)

**Comment by findstevehere** [comment]
wow so simple even thanks! have a few H265 files but oh well, will use a workaround with VLC.

cheers

**Comment by findstevehere** [comment]
hi again. I have to reinstall this wrapper. Video station is installed. It is restartring codecpack and now videostation and taking some some time and that’s  a good sign. First time didnt work as there were numerous errors, This time good. works fine. wondering why you said you have to uninstall and install video station. Didnt do that and it works fine.

thanks
steve

**Comment by AlexPresso** [comment]
Reinstalling VideoStation and AME is only required in case you already have patched files (the patcher isn't handling already patched files and it may break VideoStaion or throw errors while patching).
But if you only updated VideoStation / AME, you already have a "fresh" install, so you can directly run the patcher again

**Pull request merged**
