### PR TITLE
Update script to work with DS218play

### PR DESCRIPTION
**Pull request by twardakm**
Please refer to my comment for details:

https://gist.github.com/BenjaminPoncet/bbef9edc1d0800528813e75c1669e57e#gistcomment-3778798

### CODE REVIEW

**Comment by AlexPresso** [comment]
Hey, thanks for the PR, I'll test it tomorrow.
The `libavfilter.so.56` comes from the unpacked library of VideoStation 2.3.4, that's why it has that name.
I'm also using a DS218Play and not having any problem related to `libavfilter.so.5` but I'm not using CodecPack so maybe that is related to it.

**Comment by twardakm** [comment]
Oh, I didn't check VideoStation 2.3.4 package before, but now I did and I have `libavfilter.so.5` there as well:
```bash
~/Downloads/VideoStation-armv8-2.3.4-1468/package (1).tgz/lib/ffmpeg [20:46:23] 
$ ll
total 12284
-rw-r--r-- 1 marcin marcin 8976834 2017-08-28  libavcodec.so.56
-rw-r--r-- 1 marcin marcin   12434 2017-08-28  libavdevice.so.56
-rw-r--r-- 1 marcin marcin 1155249 2017-08-28  libavfilter.so.5
-rw-r--r-- 1 marcin marcin 1755241 2017-08-28  libavformat.so.56
-rw-r--r-- 1 marcin marcin  291436 2017-08-28  libavutil.so.54
-rw-r--r-- 1 marcin marcin   45194 2017-08-28  libpostproc.so.53
-rw-r--r-- 1 marcin marcin   65786 2017-08-28  libswresample.so.1
-rw-r--r-- 1 marcin marcin  250074 2017-08-28  libswscale.so.3
```

**Comment by AlexPresso** [comment]
Oh, you're right ! Then I think I was tired and mistyped it when I created the repo

**Comment by twardakm** [comment]
Hah, I guess this file is just not needed then, since it worked for you :sweat_smile: 

This symbolic link though is probably needed when you use `CodecPack`

**Pull request merged**
