### PR TITLE
New wrapper

### LINKED ISSUE #18: [BUG] HEVC + [DTS or EAC3 or TrueHD] not being transcoded once patched (GStreamer)
Refer to the prior list branched to this question
https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/issues/15#issuecomment-974916202

I have been patching VideoStation with Vincent compiled ffmpeg 4.x and videos have been playing fine in eac3, dts, truehd. Now, suddenly, they don't play anymore with most recent DSM update. I'm unsure why but did find a few wrinkles where there's additional ffmpeg binaries. Even after linking them to the ffmpeg 4.x community forum binary, eac3 videos still will not play. 

Alex suggested running the patcher.sh file. Looking through it, it seems identical to the steps I did except the patcher.sh puts a script inplace of the ffmpeg in /var/packages/VideoStation/target/bin directory which then goes through some logic to call the correct binary. This practice was used in the past prior to Vincent doing a native compile for the ffmpeg binary with supports all the options synology uses. Thus, the script was no longer needed. 

It appears that somewhere in the libraries (not modified by the script) there are still some prohibited codecs (e.g. eac3, dts, truehd). The real question is where are these codecs listed?

Here's the mods for ffmpeg4:

sudo -i
#
# these are a soft link to the ffmpeg binary that can be used instead.
#
mv /var/packages/VideoStation/target/bin/ffmpeg /var/packages/VideoStation/target/bin/ffmpeg.old
ln -sf /var/packages/ffmpeg/target/bin/ffmpeg /var/packages/VideoStation/target/bin/ffmpeg
mv /var/packages/CodecPack/target/bin/ffmpeg41 /var/packages/CodecPack/target/bin/ffmpeg41.old
ln -sf /var/packages/ffmpeg/target/bin/ffmpeg /var/packages/CodecPack/target/bin/ffmpeg41
mv /var/packages/VideoStation/target/bin/ffprobe /var/packages/VideoStation/target/bin/ffprobe.old
ln -sf /var/packages/ffmpeg/target/bin/ffprobe /var/packages/VideoStation/target/bin/ffprobe
mv /var/packages/VideoStation/target/bin/vainfo /var/packages/VideoStation/target/bin/vainfo.old
ln -sf /var/packages/ffmpeg/target/bin/vainfo /var/packages/VideoStation/target/bin/vainfo
cp -p /var/packages/VideoStation/target/lib/libsynovte.so /var/packages/VideoStation/target/lib/libsynovte.so.old
sed -i 's/eac3/BLAH/' /var/packages/VideoStation/target/lib/libsynovte.so
sed -i 's/dts/ZAP/' /var/packages/VideoStation/target/lib/libsynovte.so
sed -i 's/truehd/IGNORE/' /var/packages/VideoStation/target/lib/libsynovte.so

### LINKED ISSUE #29: DSM 7.1-42661 Update 1 spin on Chromecast
Hi !
First, great job, it work well, before i update the Syno ;)

Advanced Media Extensions version: 2.0.0-1017
VideoStation version: 3.0.3-2084
SynoCommunity FFMPEG version: 4.4.2-43
Synology model: DS220+
DSM 7.1-42661 Update 1

I Can launch movie (EAC3) on DSVideoStation on Windows (need external player like VLC), Iphone and Ipad with no error, like before update

But, i can't cast to Chromecast (Bbox Miami) whith EAC3 audio, AAC_LC work.

Any idea ? i have already test the last closed issue's solution (dsm 7.1 codec not working #26)

### LINKED ISSUE #36: offline transcoding fails (unknown encoder aac)
hello alex,

i have a ds1520+ and when i use your new patch i get the error "the operation could not be performed. possibly the network connection is unstable..." when transcoding offline.
i have the same error with a ds720+ as well
but strangely enough the playback works fine.
videostation and ame were already reinstalled, but there was no change.
all packages are up to date and dsm too.

here the ffmpeg.log

https://gist.github.com/Fabian1601/ceda916cf53711f9a351fc9f1fe46bf4

according to the log it does not know the aac encoder.

greetings

### LINKED ISSUE #39: [BUG] dvvideo plays sound but black video
**System details**
- Synology model: DS3617xs
- DSM version: 6.2
- SynoCommunity FFMPEG Version: 4.4.2-43
- VideoStation version: 2.4.10-1632
- Advanced Media Extensions version: none

**Describe the bug**
A video using dvvideo codex shows a black image but plays the sound.

```
Resolution: 720 x 576
Container: dv
Videocodec: dvvideo
Audiocodec: pcm_s16le
Videobitrate: 28141.7 Kbps
```

**FFMPEG logs**
https://gist.github.com/Subtixx/aedb7818be53f67054826f5df7018280

### PR DESCRIPTION
**Pull request by AlexPresso**
New wrapper implementation to replace Advanced Media Extensions gstreamer and ffmpeg

Fixes #29
Fixes #36 
Fixes #39
Related to #15 
Will fix #18 

Needs a custom implementation of GStreamer: https://github.com/SynoCommunity/spksrc/pull/5298

### CODE REVIEW

**Comment by AlexPresso** [comment]
This pull request won't be merged soon because I need to make my own gstreamer SynoCommunity package implementation. The default one doesn't include DTS decoders and I would like to keep AME usable by other apps.

**Comment by AlexPresso** [comment]
Since the new ffmpeg wrapper seems to be ready and fixes half of the issues, I'll merge it to the main branch.
The new GStreamer implementation will be done in another pull request

**Review by dadami-io — APPROVED** [review]
working very nice

**Comment by enr00ted** [comment]
> working very nice

Hoping to see it merged :)

**Comment by AlexPresso** [comment]
Yeah, me too :) I'm just waiting for the SynoCommunity to release the GStreamer package with OMX support, when it'll be ready, everything will work on every architectures

**Comment by findstevehere** [comment]
> Yeah, me too :) I'm just waiting for the SynoCommunity to release the GStreamer package with OMX support, when it'll be ready, everything will work on every architectures

gstreamer needs to be installed from community? how? it's not in package centre

**Comment by AlexPresso** [comment]
It's a work in progress, not yet available, that's why this PR is still open ;)

**Comment by findstevehere** [comment]
thanks..... see this gets confusing when you read all these different threads and fixes etc etc.... shows somewhere gstreamer or whatever is a dependency... will  try this again

**Comment by ner00** [comment]
> It's a work in progress, not yet available, that's why this PR is still open ;)

@AlexPresso  Please consider removing gstreamer dependency from the readme, it's actually confusing because it is not a dependency, and probably won't be for a while.

**Comment by findstevehere** [comment]
oh god here it is… first problem already

**Comment by ner00** [comment]
> oh god here it is… first problem already

@findstevehere Maybe it should be better if you open an issue here: https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/issues

**Comment by findstevehere** [comment]
thanks - googling how to change host key on mac…. never had this issue the first time weird oh well

**Comment by AlexPresso** [comment]
> > It's a work in progress, not yet available, that's why this PR is still open ;)
> 
> @AlexPresso Please consider removing gstreamer dependency from the readme, it's actually confusing because it is not a dependency, and probably won't be for a while.

my bad this gstreamer dependency is not supposed to be out of this PR for now ahah, must have merged it by mistake, I'll remove it, thx

**Comment by findstevehere** [comment]
sure np guess Im not crazy


but invariably it’s always this sort of crap and gets so frustrating…..

**Comment by findstevehere** [comment]
oh hey thanks so much for your quick responses and help… found out how to fix SSH remote host ID error - easy fix just needed to delete the lines from the known hosts file. then used patch and looks good to go… will test out… guess it was that HOST file change error that got me last time.

cheers

**Comment by AlexPresso** [comment]
Hey there,
Currently implementing the GStreamer patch based on @nap-liu informations in following issue: #53 
Status:
- DTS : ✅
- H265 / HEVC : ✅
- TrueHD : Working on...
- EAC3 : Working on...

**Pull request merged**
